# environment.yml: Mandatory dependencies only.
channels:
- conda-forge
- pytorch
- nvidia
- nodefaults

dependencies:
# Libraries to manipulate data
- dask
- xarray
- netcdf4
# Deep learning and machine learning libraries
- pytorch
- torchvision
- torchaudio
- pytorch-cuda=11.8
- tensorboard
- accelerate
- diffusers
- transformers
- huggingface_hub
- aim
# Visualization libraries
- cartopy
- matplotlib
- seaborn
# Metrics libraries
- evaluate
- scikit-image
# Libraries for utilities
- mlflow
- pydantic
- pyyaml
- tqdm
# Types for mypy
- types-requests
- types-pyyaml
# Software
- git-lfs
