# environment.yml: Mandatory dependencies only.
channels:
- conda-forge
- nodefaults

dependencies:
# Libraries to manipulate data
- dask
- xarray
- netcdf4
# Deep learning and machine learning libraries
- pytorch
- tensorboard
# Visualization libraries
- cartopy
- matplotlib
- seaborn
# Metrics libraries
- xskillscore
# Libraries for utilities
- pyyaml
- tqdm
