# environment.yml: Mandatory dependencies only.
channels:
- conda-forge
- nodefaults

dependencies:
# Libraries to manipulate data
- dask
- xarray
- netcdf4
# Deep learning and machine learning libraries
- pytorch
# Validation libraries
- matplotlib
- seaborn
# Libraries for utilities
- pyyaml

# Libraries that can only be installed with pip
- pip:
  - labml
