# Data configuration
data_configuration:
  # Features configuration
  features_configuration:
    variables:
    - t2m
    data_name: era5
    add_auxiliary: False
    spatial_resolution: "025deg"
    spatial_coverage:
      longitude: [ -8.35, 6.6]
      latitude: [ 46.45, 35.50 ]
    apply_standardization: True
    data_dir: /home/santacruzm/Git/DeepR/tests/data/features/
  # Label configuration
  label_configuration:
    variable: t2m
    data_name: cerra
    spatial_resolution: "005deg"
    apply_standardization: True
    spatial_coverage:
      longitude: [ -6.85, 5.1]
      latitude: [ 44.95, 37 ]
    data_dir: /home/santacruzm/Git/DeepR/tests/data/labels/
  # Common data configuration
  common_configuration:
    temporal_coverage:
      start: 1985-01
      end: 2020-12
      frequency: MS
    data_split:
      test: 0.2
      validation: 0.3
# Training configuration
training_configuration:
  type: end2end
  model_configuration:
    neural_network:
      class_name: ConvSwin2SR
      kwargs:
        embed_dim: 128
        depths: [4, 4, 4, 4]
        num_heads: [4, 4, 4, 4]
        patch_size: 1
        window_size: 5 # divisor of input dims (1, 2 and 5 for images (20, 30))
        num_channels: 1
        img_range: 1
        resi_connection: "1conv"
        upsampler: "pixelshuffle"
        interpolation_method: "bicubic"
        hidden_dropout_prob: 0.0
        upscale: 5 # For this method, must be power of 2.
  training_parameters:
    num_epochs: 200
    gradient_accumulation_steps: 1
    learning_rate: 0.0001
    lr_warmup_steps: 500
    mixed_precision: "fp16"
    output_dir: "swin2sr-1985_2020"
    device: cpu
    push_to_hub: False
    seed: 2023
    save_image_epochs: 5
    save_model_epochs: 10
