# Data configuration
data_configuration:
  # Features configuration
  features_configuration:
    variables:
    - t2m
    data_name: era5
    spatial_resolution: "025deg"
    add_auxiliary:
      time: true
      lsm-low: true
      orog-low: true
      lsm-high: true
      orog-high: true
    spatial_coverage:
      longitude: [-8.35, 6.6]
      latitude: [46.45, 35.50]
    standardization:
      to_do: true
      cache_folder: /PATH/TO/.cache_reanalysis_scales
      method: domain-wise # pixel-wise, domain-wise, landmask-wise
    data_location: /PATH/TO/features/
    land_mask_location: /PATH/TO/static/land-mask_ERA5.nc
    orography_location: /PATH/TO/static/orography_ERA5.nc
  # Label configuration
  label_configuration:
    variable: t2m
    data_name: cerra
    spatial_resolution: "005deg"
    spatial_coverage:
      longitude: [-6.85, 5.1]
      latitude: [44.95, 37]
    standardization:
      to_do: true
      cache_folder: /PATH/TO/.cache_reanalysis_scales
      method: domain-wise # pixel-wise, domain-wise, landmask-wise
    data_location: /PATH/TO/labels/
    land_mask_location: /PATH/TO/static/land-mask_CERRA.nc
    orography_location: /PATH/TO/static/orography_CERRA.nc
  # Common data configuration
  split_coverages:
    train:
      start: 1981-01
      end: 2013-12
      frequency: MS
    validation:
      start: 2014-01
      end: 2017-12
      frequency: MS
# Training configuration
training_configuration:
  type: end2end
  model_configuration:
    neural_network:
      class_name: ConvSwin2SR
      kwargs:
        embed_dim: 128
        depths: [4, 4, 4, 4]
        num_heads: [4, 4, 4, 4]
        patch_size: 1
        window_size: 5 # divisor of input dims (1, 2 and 5 for images (20, 30))
        num_channels: 1
        img_range: 1
        resi_connection: "1conv"
        upsampler: "pixelshuffle"
        interpolation_method: "bicubic"
        hidden_dropout_prob: 0.0
        upscale: 5 # For this method, must be power of 2.
  training_parameters:
    num_epochs: 100
    gradient_accumulation_steps: 4
    learning_rate: 0.0001
    lr_warmup_steps: 500
    mixed_precision: "fp16"
    hf_repo_name: predictia/europe_reanalysis_downscaler_convswin2sr
    output_dir: "swin2sr-1985_2020"
    device: cpu
    push_to_hub: false
    seed: 2023
    save_image_epochs: 5
    save_model_epochs: 10
