# Data configuration
data_configuration:
  # Features configuration
  features_configuration:
    variables:
    - t2m
    data_name: era5
    add_auxiliary: true
    spatial_resolution: "025deg"
    spatial_coverage:
      longitude: [-8.35, 6.6]
      latitude: [46.45, 35.50]
    apply_standardization: true
    data_dir: /PATH/TO/features/
  # Label configuration
  label_configuration:
    variable: t2m
    data_name: cerra
    spatial_resolution: "005deg"
    apply_standardization: true
    spatial_coverage:
      longitude: [-6.85, 5.1]
      latitude: [44.95, 37]
    data_dir: /PATH/TO/labels/
  # Common data configuration
  common_configuration:
    temporal_coverage:
      start: 1985-01
      end: 2020-12
      frequency: MS
    data_split:
      test: 0.2
      validation: 0.3
# Training configuration
training_configuration:
  type: diffusion
  model_configuration:
    eps_model:
      class_name: diffusers.UNet2DModel
      kwargs:
        block_out_channels: [32, 64, 128, 128]
        down_block_types: [DownBlock2D, AttnDownBlock2D, AttnDownBlock2D, AttnDownBlock2D]
        up_block_types: [AttnUpBlock2D, AttnUpBlock2D, AttnUpBlock2D, UpBlock2D]
        layers_per_block: 2
        time_embedding_type: positional
        #class_embed_type: "none" # timestep
        num_class_embeds: 24 # Encode hours as table of 24 embeddings
        in_channels: 2
    #trained_obs_model:
    #  class_name: ConvBilinear
    #  model_dir: predictia/europe_reanalysis_downscaler_convbaseline
    scheduler:
      class_name: LMSDiscreteScheduler
      kwargs:
        num_train_timesteps: 1000
        beta_start: 0.0001
        beta_end: 0.02
        beta_schedule: linear
        prediction_type: epsilon
  training_parameters:
    num_epochs: 100
    gradient_accumulation_steps: 1
    learning_rate: 0.0001
    lr_warmup_steps: 500
    mixed_precision: "fp16"
    hour_embed_type: class # none, timestep, positional, cyclical, class
    output_dir: "cddpm-probando-tiny"
    device: cpu
    push_to_hub: false
    seed: 2023
    save_image_epochs: 10
    num_samples: 3
    save_model_epochs: 30
