# Data configuration
data_configuration:
  # Features configuration
  features_configuration:
    variables:
    - t2m
    data_name: era5
    spatial_resolution: "025deg"
    add_auxiliary:
      time: true
      lsm-low: true
      orog-low: true
      lsm-high: true
      orog-high: true
    spatial_coverage:
      longitude: [-8.35, 6.6]
      latitude: [46.45, 35.50]
    standardization:
      to_do: true
      cache_folder: /PATH/TO/.cache_reanalysis_scales
      method: domain-wise
    data_location: /PATH/TO/features/
    land_mask_location: /PATH/TO/static/land-mask_ERA5.nc
    orography_location: /PATH/TOstatic/orography_ERA5.nc
  # Label configuration
  label_configuration:
    variable: t2m
    data_name: cerra
    spatial_resolution: "005deg"
    standardization:
      to_do: true
      cache_folder: /PATH/TO/.cache_reanalysis_scales
      method: domain-wise
    spatial_coverage:
      longitude: [-6.85, 5.1]
      latitude: [44.95, 37]
    data_location: /PATH/TO/labels/
    land_mask_location: /PATH/TO/static/land-mask_CERRA.nc
    orography_location: /PATH/TO/static/orography_CERRA.nc
  # Common data configuration
  common_configuration:
    temporal_coverage:
      start: 1981-01
      end: 2018-12
      frequency: MS
    data_split:
      test: 0.0
      validation: 0.2
# Training configuration
training_configuration:
  type: diffusion
  model_configuration:
    eps_model:
      class_name: diffusers.UNet2DModel
      kwargs:
        block_out_channels: [16, 24, 32]
        down_block_types: [DownBlock2D, AttnDownBlock2D, AttnDownBlock2D]
        up_block_types: [AttnUpBlock2D, AttnUpBlock2D, UpBlock2D]
        layers_per_block: 2
        time_embedding_type: positional
        #class_embed_type: "none" # timestep
        num_class_embeds: 24 # Encode hours as table of 24 embeddings
        in_channels: 2
        norm_num_groups: 4
    #trained_obs_model:
    #  class_name: ConvBilinear
    #  model_dir: predictia/europe_reanalysis_downscaler_convbaseline
    scheduler:
      class_name: LMSDiscreteScheduler
      kwargs:
        num_train_timesteps: 1000
        beta_start: 0.0001
        beta_end: 0.02
        beta_schedule: linear
        prediction_type: epsilon
        rescale_betas_zero_snr: true
        timestep_spacing: trailing
  training_parameters:
    num_epochs: 30
    batch_size: 4
    gradient_accumulation_steps: 4
    learning_rate: 0.001
    lr_warmup_steps: 500
    mixed_precision: "fp16"
    hour_embed_type: class # none, timestep, positional, cyclical, class
    hf_repo_name: "predictia/MODEL_REPO_NAME"
    output_dir: "cddpm-probando-tiny"
    device: cuda
    push_to_hub: true
    seed: 2023
